apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dnsp-home
  labels:
    app: dnsp-home
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dnsp-home
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dnsp-home
      name: dnsp-home
    spec:
      containers:
      - args:
        - "--blacklist=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
        - "--poll=72h"
        - "--resolve=8.8.8.8,4.4.4.4"
        image: "docker.io/integrii/dnsp"
        imagePullPolicy: Always
        name: "dnsp-home"
        readinessProbe:
          exec:
            command:
            - "nslookup"
            - "google.com."
            - "127.0.0.1"
          initialDelaySeconds: 10
          periodSeconds: 1
        livenessProbe:
          exec:
            command:
            - "nslookup"
            - "google.com."
            - "127.0.0.1"
          initialDelaySeconds: 360
          periodSeconds: 1
      terminationGracePeriodSeconds: 15
