apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dnsp-home
  labels:
    app: dnsp-home
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: dnsp-home
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dnsp-home
      name: dnsp-home
    spec:
      terminationGracePeriodSeconds: 15
      containers:
      - args:
        - --blacklist=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
        - --poll=72h
        - --resolve=8.8.8.8,4.4.4.4
        name: "dnsp-home"
        image: "docker.io/integrii/dnsp"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
        readinessProbe:
          exec:
            command:
            - "nslookup"
            - "google.com."
            - "127.0.0.1"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 1
        livenessProbe:
          exec:
            command:
            - "nslookup"
            - "google.com."
            - "127.0.0.1"
          initialDelaySeconds: 120
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 1
        ports:
          - containerPort: 53
            name: dns-server
            protocol: UDP
