apiVersion: v1
kind: Service
metadata:
  labels:
    app: dnsp-home
  name: dnsp-home
spec:
  ports:
  - port: 53
    protocol: UDP
    targetPort: dns-server
  selector:
    app: dnsp-home
  type: LoadBalancer
